name: jdr_gamemaster_app
description: An app that makes it easier for gamemasters to manage DND Beyond based campaigns.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  logging: ^1.3.0
  path_provider: ^2.1.5
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
