name: Build and Release

jobs:
  # Verify build on commit
  verify-build:
    if: github.event_name == 'push'
    name: Verify Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      # Install Linux dependencies if on Linux
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev clang cmake pkg-config

      # Enable desktop builds
      - name: Enable desktop builds
        run: |
          flutter config --enable-windows-desktop
          flutter config --enable-linux-desktop

      # Just verify the build works
      - name: Verify Windows build
        if: matrix.os == 'windows-latest'
        run: flutter build windows --release

      - name: Verify Linux build
        if: matrix.os == 'ubuntu-latest'
        run: flutter build linux --release

  # Full build and package on manual release
  build-release:
    if: github.event_name == 'workflow_dispatch'
    name: Build Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      # Install Linux dependencies if on Linux
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev clang cmake pkg-config

      # Enable desktop builds
      - name: Enable desktop builds
        run: |
          flutter config --enable-windows-desktop
          flutter config --enable-linux-desktop

      # Build and package Windows
      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: flutter build windows --release

      - name: Install Inno Setup
        if: matrix.os == 'windows-latest'
        run: choco install innosetup -y

      - name: Create Windows Installer
        if: matrix.os == 'windows-latest'
        env:
          APP_VERSION: ${{ inputs.version }}
        run: |
          cd windows
          iscc.exe /Q setup.iss

      - name: Upload Windows Installer
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: windows-installer
          path: windows/Output/JDR-Gamemaster-App-*.exe

      # Build and package Linux
      - name: Build and Package Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          flutter build linux --release
          cd build/linux/x64/release/bundle
          zip -r ../../../../../linux-release.zip *

      - name: Upload Linux Build
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: linux-release.zip

  # Create Release
  create-release:
    name: Create Release
    needs: build-release
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ inputs.version }}
          name: Release v${{ inputs.version }}
          body: ${{ inputs.release_notes }}
          draft: false
          prerelease: false
          files: |
            windows-installer/JDR-Gamemaster-App-*.exe
            linux-build/linux-release.zip

on:
  # Just verify build on push
  push:
    branches: ["main"]

  # Full build and release on manual trigger
  workflow_dispatch:
    inputs:
      version:
        description: "Version number (e.g., 1.0.0)"
        required: true
        type: string
      release_notes:
        description: "Release notes"
        required: false
        type: string
        default: "No release notes provided"
